### ISSUE TITLE
ReactDOMServer

### ISSUE THREAD

**Issue by dburles** [lukejacksonn/es-react#2]
Thanks for putting this together! Would it be difficult to also expose ReactDOMServer? I'm wanting to experiment with SSR.

**Comment by lukejacksonn** [comment]
Hey man! Errm, I have never used ReactDOMServer.. if you can find it in one of the `src` files then it should be exposable but I don't know how/if it would work for SSR

**Comment by dburles** [comment]
I think it might have to be bundled separately as it's normally imported by path e.g:
`import ReactDOMServer from 'react-dom/server';` it would be great in that with [Deno](https://deno.land/), we can use url imports and make use of it for server side rendering.

**Comment by Soremwar** [comment]
> 
> 
> I think it might have to be bundled separately as it's normally imported by path e.g:
> `import ReactDOMServer from 'react-dom/server';` it would be great in that with [Deno](https://deno.land/), we can use url imports and make use of it for server side rendering.

Reached the exact same dead-end man. Found this and tough i'd finally set up my Deno project with React but RDS was missing.

So long for the try.

**Comment by lukejacksonn** [comment]
Hey folks 👋 things have changed quite dramatically in the last few commits to this repo. The assets/exports are now generated programatically (thanks to #6 by @kitten). We now include packages like `prop-types` and `react-is` in the deploy, so adding `react-dom/server` might be more trivial now.

Take a look and let me know what you think!

**Comment by lukejacksonn** [comment]
Hey @dburles 👋  hopefully this is fixed for you thanks to @iAmNathanJ and #13. Closing here. Let me know if you have any further issues!
